# areas: jobs, economy
# shared-job-achievements (ROADMAP row 30): A takes an order with a money bonus, B takes a part of its car off and puts
# it back and moves the car to the other lift, A ends the completed job: B is awarded the finished order and the
# money bonus once, and A, the finisher, is sent nothing (stats-trace counts at SteamAchievements.IncrementStat; the
# Steam writes stay blocked). The jobs end through job-end-direct like in the other job scenarios: the game's own
# EndJob stops at its car checks on a test car, so the finisher's own vanilla count is not run here. A finishes a job alone: B gets nothing. With "jobs stats-to garage" B gets the next job
# alone too, and after a restart with job_stats_to = garage in the config as well. B works on a car and disconnects
# before A finishes: no award and no error, and nothing after B joins again (a guard).
param($Ctx)

Import-Module (Join-Path $PSScriptRoot "..\ScaleSession.psm1")

$a, $b = $Ctx.Instances
$failures = @()
function Check([bool]$Condition, [string]$Message) { if (-not $Condition) { $script:failures += "FAIL: $Message"; Write-Host "FAIL: $Message" -ForegroundColor Red } else { Write-Host "ok: $Message" } }
function Cmd([string]$Name, [string]$Verb, [string]$Arguments = "") { Send-HarnessCommand -Instance $Name -Verb $Verb -Arguments $Arguments }
function Save([string]$Label, $Value) { $Value | ConvertTo-Json -Depth 10 | Set-Content -LiteralPath (Join-Path $Ctx.RunDir "stats_$Label.json") -Encoding utf8 }

function Wait-InGarage([string]$Name) {
    Wait-HarnessStatus -Instance $Name -TimeoutSec 300 -What "garage, sync acked" -Condition {
        param($s) $s.connectionValid -and $s.syncAcked -and $s.scene -eq "garage" -and $s.playable
    } | Out-Null
}
function Jobs([string]$Name) { (Cmd $Name dump).jobs }
function Wait-Ready([string]$Name, [int]$Loader) {
    $deadline = (Get-Date).AddSeconds(120)
    do {
        $r = try { Cmd $Name car-ready "$Loader" } catch { $null }
        if ($r.state -eq "Ready" -and $r.loaded) { return $true }
        Start-Sleep -Milliseconds 500
    } while ((Get-Date) -lt $deadline)
    return $false
}
function Counts([string]$Name) { (Cmd $Name stats-trace report).counts }
function Connect-Both {
    foreach ($name in $Ctx.Instances) {
        Wait-HarnessStatus -Instance $name -TimeoutSec 300 -What "main menu" -Condition { param($s) $s.scene -eq "Menu" -and $s.playable } | Out-Null
    }
    Connect-HarnessInstance $a; Wait-InGarage $a
    Connect-HarnessInstance $b; Wait-InGarage $b
    foreach ($name in $Ctx.Instances) {
        Cmd $name guard-set "Off" | Out-Null
        Cmd $name orders-autogen "off" | Out-Null
        Cmd $name stats-trace "on" | Out-Null
    }
}

# A takes a new order (generated by A, the first player in the garage); returns @{ Id; Loader }.
function Take-Order([string]$Bonus = "-") {
    $before = @((Jobs $a).orders | ForEach-Object { $_.id })
    Cmd $a orders-generate "- $Bonus" | Out-Null
    $deadline = (Get-Date).AddSeconds(30)
    do {
        Start-Sleep -Milliseconds 700
        $new = @((Jobs $a).orders | Where-Object { -not $_.IsMission -and $before -notcontains $_.id })
    } while ($new.Count -eq 0 -and (Get-Date) -lt $deadline)
    if ($new.Count -eq 0) { throw "no new order" }
    $id = $new[0].id
    $mark = Get-ServerLogMark
    Cmd $a orders-accept "$id" | Out-Null
    $started = Wait-ServerLog -Pattern "Job $id started by client \d+ on loader (\d+)" -After $mark -TimeoutSec 90
    $loader = [int]([regex]::Match($started, "on loader (\d+)").Groups[1].Value)
    Check ((Wait-Ready $a $loader) -and (Wait-Ready $b $loader)) "job $id's car is Ready on loader $loader for both"
    Start-Sleep -Seconds 2
    return @{ Id = $id; Loader = $loader }
}

function Finish([hashtable]$Job) {
    $mark = Get-ServerLogMark
    Cmd $a job-end-direct "$($Job.Id)" | Out-Null
    $ended = try { Wait-ServerLog -Pattern "Job $($Job.Id) ended by client \d+: .* completed (True|False)" -After $mark -TimeoutSec 30 } catch { $null }
    Check ($ended -match "completed True") "job $($Job.Id) ended completed ($ended)"
    $awarded = try { Wait-ServerLog -Pattern "\[Jobs\] Job $($Job.Id) stats" -After $mark -TimeoutSec 10 } catch { $null }
    Start-Sleep -Seconds 3
    return $awarded
}

function Touch-Car([string]$Name, [hashtable]$Job) {
    $key = @(Cmd $Name vfx-parts "$($Job.Loader)")[0].key
    Cmd $Name part-fast-unmount "$($Job.Loader) $key" | Out-Null
    Start-Sleep -Seconds 3
    Cmd $Name part-fast-mount "$($Job.Loader) $key" | Out-Null
    Start-Sleep -Seconds 3
    return $key
}

# Orders roll their own bonuses, so the expected counts are the stats the server's award line lists (all 0 for "").
function Expect-Award([string]$Name, [string]$What, [string]$AwardLine) {
    $listed = @(([regex]::Match("$AwardLine", "stats \[([^\]]*)\]").Groups[1].Value -split ",\s*") | Where-Object { $_ })
    $c = Counts $Name
    $wrong = @("stat_finish_order", "stat_bonus_exp", "stat_bonus_money", "stat_finish_allmissions" | Where-Object { $c.$_ -ne $(if ($listed -contains $_) { 1 } else { 0 }) })
    Check ($wrong.Count -eq 0) "$Name`: $What (expected [$($listed -join ', ')]; counted $($c | ConvertTo-Json -Compress))"
}

Connect-Both
$trace = Cmd $a stats-trace report
Check ($trace.patched) "SteamAchievements.IncrementStat can be patched for the trace ($($trace.error))"
Send-ServerCommand "money set 500000"

# 1. A takes a money-bonus order, B works on its car and moves it to the other lift, A finishes it completed.
$job = Take-Order "money"
$key = Touch-Car $b $job
Write-Host "B took $key off and put it back"
Cmd $b car-move "$($job.Loader) CarLifter2" | Out-Null
Start-Sleep -Seconds 6
$mark = Get-ServerLogMark
Send-ServerCommand "jobs contributors $($job.Id)"
$contributors = try { Wait-ServerLog -Pattern "job $($job.Id): .*stats go to" -After $mark -TimeoutSec 10 } catch { $null }
Check (([regex]::Matches("$contributors", "(guid|steam):[^,;]+")).Count -ge 2) "the server lists A and B as contributors of job $($job.Id) ($contributors)"
$awarded = Finish $job
Check ($awarded -match "clients \d+") "the server awarded the job's stats to B ($awarded)"
Check ($awarded -match "stat_finish_order" -and $awarded -match "stat_bonus_money") "the award holds the finished order and the money bonus ($awarded)"
Expect-Award $b "awarded the job's stats once" $awarded
Expect-Award $a "the finisher is sent no award" ""

# 2. A finishes a job alone: B gets nothing; with "jobs stats-to garage" B gets the next one.
foreach ($name in $Ctx.Instances) { Cmd $name stats-trace "on" | Out-Null }
$job = Take-Order
Finish $job | Out-Null
Expect-Award $b "nothing for a job B did not touch" ""
Expect-Award $a "the finisher is sent no award" ""
Send-ServerCommand "jobs stats-to garage"
$job = Take-Order
$awarded = Finish $job
Expect-Award $b "with stats-to garage, the stats of a job B did not touch" $awarded

# The rule from the config survives a restart.
Set-ServerConfigValues $Ctx.ServerDir @{ job_stats_to = "garage" }
$mark = Get-ServerLogMark
Restart-TestServer
$summary = try { Wait-ServerLog -Pattern "job stats to garage" -After 0 -TimeoutSec 60 } catch { $null }
Check ([bool]$summary) "the restarted server reads job_stats_to = garage ($summary)"
Connect-Both
$job = Take-Order
$awarded = Finish $job
Expect-Award $b "after the restart, the stats of a job B did not touch" $awarded

# 3. Guard: B works on a car and leaves before A finishes; nothing is awarded later.
Send-ServerCommand "jobs stats-to contributors"
foreach ($name in $Ctx.Instances) { Cmd $name stats-trace "on" | Out-Null }
$job = Take-Order
Touch-Car $b $job | Out-Null
Cmd $b disconnect | Out-Null
Start-Sleep -Seconds 3
$awarded = Finish $job
Check ($awarded -match "nobody besides the finisher") "with B gone the server awards nobody else ($awarded)"
Cmd $b to-menu | Out-Null
Wait-HarnessStatus -Instance $b -TimeoutSec 120 -What "B in the menu" -Condition { param($s) $s.scene -eq "Menu" -and $s.playable } | Out-Null
Connect-HarnessInstance $b; Wait-InGarage $b
Cmd $b stats-trace "on" | Out-Null
Start-Sleep -Seconds 5
Expect-Award $b "nothing awarded after joining again" ""
$errors = @(Get-ServerLogLines | Where-Object { $_ -match "\[(ERROR|EXCEPTION)\]" })
Check ($errors.Count -eq 0) "no server errors ($($errors | Select-Object -First 3))"

$Ctx.Result.notes += $failures
$Ctx.Result.passed = ($failures.Count -eq 0)
