# areas: jobs
# Story missions (row 16 review B2/M1/M2): the server starts without a save, so the session is fresh. The first story
# mission appears exactly once on both clients and is generated by the order generator only. It cannot be declined:
# the orders window does nothing, and a decline packet is refused by the server, which answers with the jobs state.
# B takes it and finishes it like a job; the server counts the finished mission for both. With the regular orders at
# the generator's limit, the next mission still appears (the order limit does not apply to missions).
param($Ctx)

$a, $b = $Ctx.Instances
$failures = @()
function Check([bool]$Condition, [string]$Message) { if (-not $Condition) { $script:failures += "FAIL: $Message"; Write-Host "FAIL: $Message" -ForegroundColor Red } else { Write-Host "ok: $Message" } }

function Wait-InGarage([string]$Name) {
    Wait-HarnessStatus -Instance $Name -TimeoutSec 300 -What "garage, sync acked" -Condition {
        param($s) $s.connectionValid -and $s.syncAcked -and $s.scene -eq "garage" -and $s.playable
    } | Out-Null
}

function Jobs([string]$Name) { (Send-HarnessCommand -Instance $Name -Verb dump).jobs }
function Missions($Jobs) { @($Jobs.orders | Where-Object { $_.IsMission }) }
function Regular($Jobs) { @($Jobs.orders | Where-Object { -not $_.IsMission }) }

function Wait-Jobs([string]$What, [scriptblock]$Condition, [int]$TimeoutSec = 30) {
    $deadline = (Get-Date).AddSeconds($TimeoutSec)
    do {
        Start-Sleep -Milliseconds 700
        $ja = Jobs $a
        $jb = Jobs $b
        $sa = $ja | ConvertTo-Json -Depth 5 -Compress
        $sb = $jb | ConvertTo-Json -Depth 5 -Compress
        if ($sa -eq $sb -and (& $Condition $ja)) { break }
    } while ((Get-Date) -lt $deadline)
    Check ($sa -eq $sb) "$What`: A and B agree ($sa)"
    if ($sa -ne $sb) { Write-Host "  B: $sb" }
    Check ([bool](& $Condition $ja)) "$What`: expected state reached"
    return $ja
}

function Try-ServerLog([string]$Pattern, [int]$After, [int]$TimeoutSec) {
    try { Wait-ServerLog -Pattern $Pattern -After $After -TimeoutSec $TimeoutSec } catch { $null }
}

function Server-MissionsFinished {
    $mark = Get-ServerLogMark
    Send-ServerCommand "jobs"
    $line = Try-ServerLog "missions finished (\d+)" $mark 10
    if ($line -match "missions finished (\d+)") { return [int]$Matches[1] }
    return -1
}

function MissionLines([int]$After) {
    @(Get-Content -LiteralPath (Join-Path $Ctx.ServerDir "Log\Latest.txt") | Select-Object -Skip $After | Where-Object { $_ -match "\[Jobs\] Order \d+: \S+ \(mission" })
}

foreach ($name in $Ctx.Instances) {
    Wait-HarnessStatus -Instance $name -TimeoutSec 300 -What "main menu" -Condition { param($s) $s.scene -eq "Menu" -and $s.playable } | Out-Null
}

Stop-TestServer
$saves = Join-Path $Ctx.ServerDir "Saves"
if (Test-Path -LiteralPath $saves) { Move-Item -LiteralPath $saves -Destination (Join-Path $Ctx.RunDir "server_saves_before") }
Start-TestServer | Out-Null
$start = 0
Check ([bool](Try-ServerLog "No save found" 0 10)) "the server started a new session"

function ClientLog([string]$Name) { Join-Path $env:USERPROFILE "CMS21-TestInstalls\$Name\MelonLoader\Latest.log" }
$clientMarks = @{}
foreach ($name in $Ctx.Instances) { $clientMarks[$name] = @(Get-Content -LiteralPath (ClientLog $name)).Count }

Connect-HarnessInstance $a; Wait-InGarage $a
Connect-HarnessInstance $b; Wait-InGarage $b
foreach ($name in $Ctx.Instances) {
    Send-HarnessCommand -Instance $name -Verb guard-set -Arguments "Off" | Out-Null
    Send-HarnessCommand -Instance $name -Verb orders-autogen -Arguments "off" | Out-Null
}
$genA = (Get-HarnessStatus $a).isOrderGenerator
Check ($genA -and -not (Get-HarnessStatus $b).isOrderGenerator) "A is the order generator"

$jobs = Wait-Jobs "the first story mission is open on both" { param($j) @(Missions $j).Count -eq 1 } 60
$found = @(Missions $jobs)
$mission = if ($found.Count -gt 0) { $found[0] } else { $null }
if (-not $mission) {
    $Ctx.Result.notes += $failures
    $Ctx.Result.passed = $false
    return
}
Write-Host "mission order $($mission.id): $($mission.carFile)"
Start-Sleep -Seconds 3
$lines = @(MissionLines $start)
Check ($lines.Count -eq 1) "the server added exactly one mission order ($($lines -join ' | '))"
Check (-not (Try-ServerLog "Tutorial mission from client" $start 1)) "no story mission was refused as the tutorial"
$generated = @($Ctx.Instances | Where-Object {
    @(Get-Content -LiteralPath (ClientLog $_) | Select-Object -Skip $clientMarks[$_] | Select-String "\[Jobs\] Generated order .*\(mission").Count -gt 0
})
Check ($generated.Count -eq 1 -and $generated[0] -eq $a) "only the generator generated a mission ($($generated -join ', '))"
foreach ($name in $Ctx.Instances) {
    $state = Send-HarnessCommand -Instance $name -Verb missions-state
    Check ($state.MissionsFinished -eq 0 -and -not $state.CurrentMissionDone) "$name mission state: 0 finished, mission open ($($state | ConvertTo-Json -Compress))"
}

$mark = Get-ServerLogMark
Send-HarnessCommand -Instance $b -Verb orders-decline -Arguments "$($mission.id)" | Out-Null
Start-Sleep -Seconds 3
$jobs = Wait-Jobs "the orders window does not decline the mission" { param($j) @(Missions $j | Where-Object { $_.id -eq $mission.id }).Count -eq 1 } 5
Check (-not (Try-ServerLog "Order $($mission.id) declined" $mark 1)) "the server did not decline the mission"

$mark = Get-ServerLogMark
Send-HarnessCommand -Instance $b -Verb orders-decline-packet -Arguments "$($mission.id)" | Out-Null
$refused = Try-ServerLog "Decline of order $($mission.id) by client \d+ refused: Mission; answering with the jobs state" $mark 10
Check ([bool]$refused) "a decline packet for the mission is refused with the jobs state ($refused)"
$jobs = Wait-Jobs "the mission is still open on both" { param($j) @(Missions $j | Where-Object { $_.id -eq $mission.id }).Count -eq 1 } 10

$takeMark = Get-ServerLogMark
Send-HarnessCommand -Instance $b -Verb orders-accept -Arguments "$($mission.id)" | Out-Null
$jobs = Wait-Jobs "B's mission is active for both" { param($j) @($j.active | Where-Object { $_.id -eq $mission.id }).Count -eq 1 -and @(Missions $j).Count -eq 0 } 90
$active = @($jobs.active | Where-Object { $_.id -eq $mission.id })
$loader = if ($active.Count -gt 0) { $active[0].carLoaderID } else { -1 }
Write-Host "mission $($mission.id) on loader $loader"
Check (-not (Try-ServerLog "Mission order from client \d+ refused" $takeMark 1)) "the generator did not offer a second mission while B took the first"
foreach ($name in $Ctx.Instances) {
    $r = Send-HarnessCommand -Instance $name -Verb car-ready -Arguments "$loader"
    Check ($r.loaded) "$name has the mission car on loader $loader ($($r.car))"
}

Send-HarnessCommand -Instance $a -Verb stats-add -Arguments "0 9000" | Out-Null
$deadline = (Get-Date).AddSeconds(20)
do { Start-Sleep -Milliseconds 700; $level = (Send-HarnessCommand -Instance $a -Verb missions-state).level } while ($level -lt 1 -and (Get-Date) -lt $deadline)
Check ($level -ge 1) "A reached level $level, so the next mission is unlocked"

$max = (Send-HarnessCommand -Instance $a -Verb missions-state).maxOrders
$mark = Get-ServerLogMark
for ($i = 0; $i -le $max; $i++) { Send-HarnessCommand -Instance $a -Verb orders-generate -Arguments "900" | Out-Null; Start-Sleep -Milliseconds 300 }
$jobs = Wait-Jobs "the regular orders are at the limit ($max)" { param($j) @(Regular $j).Count -eq $max } 30
Check ([bool](Try-ServerLog "refused: \d+ open orders, the generator's limit is $max" $mark 5)) "a regular order over the limit was refused"

$moneyBefore = (Send-HarnessCommand -Instance $a -Verb dump).stats.money
$mark = Get-ServerLogMark
Send-HarnessCommand -Instance $b -Verb job-end-direct -Arguments "$($mission.id)" | Out-Null
$ended = Try-ServerLog "Job $($mission.id) ended by client \d+: payout (\d+)" $mark 30
Check ([bool]$ended) "the server got the end of the mission ($ended)"
Wait-Jobs "the finished mission is gone for both" { param($j) @($j.active | Where-Object { $_.id -eq $mission.id }).Count -eq 0 } 30 | Out-Null
Start-Sleep -Seconds 2
$moneyA = (Send-HarnessCommand -Instance $a -Verb dump).stats.money
$moneyB = (Send-HarnessCommand -Instance $b -Verb dump).stats.money
Check ($moneyA -eq $moneyB -and $moneyA -gt $moneyBefore) "A and B got the payout once ($moneyBefore -> A $moneyA, B $moneyB)"
$finished = Server-MissionsFinished
Check ($finished -eq 1) "the server counts one finished mission ($finished)"
foreach ($name in $Ctx.Instances) {
    $state = Send-HarnessCommand -Instance $name -Verb missions-state
    Check ($state.MissionsFinished -eq 1) "$name counts one finished mission ($($state | ConvertTo-Json -Compress))"
}

$mark = Get-ServerLogMark
Send-HarnessCommand -Instance $a -Verb orders-autogen -Arguments "on" | Out-Null
$jobs = Wait-Jobs "the next mission appears with the regular orders at the limit" { param($j) @(Missions $j).Count -eq 1 -and @(Regular $j).Count -eq $max } 60
Send-HarnessCommand -Instance $a -Verb orders-autogen -Arguments "off" | Out-Null
$next = @(Missions $jobs)
Check ($next.Count -eq 1 -and $next[0].id -ne $mission.id) "the next mission is a new order ($($next | ConvertTo-Json -Compress))"
Check (@(MissionLines $mark).Count -eq 1) "the server added the next mission once"
foreach ($name in $Ctx.Instances) {
    $state = Send-HarnessCommand -Instance $name -Verb missions-state
    Check ($state.MissionsFinished -eq 1 -and -not $state.CurrentMissionDone) "$name has the next mission open ($($state | ConvertTo-Json -Compress))"
}

$Ctx.Result.notes += $failures
$Ctx.Result.passed = ($failures.Count -eq 0)
